name: Android CI

on:
  push:
    branches:
      - 'release/*'
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type, either debug or release'
        required: false
        type: string
      flavor:
        description: 'Build flavor'
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - run: flutter pub get
      - name: Build APK
        env:
          BUILD_FLAVOR: "${{ github.event.inputs.flavor }}"
          BUILD_TYPE: "${{ github.event.inputs.buildType }}"
        run: flutter build apk --flavor "$BUILD_FLAVOR" --"$BUILD_TYPE"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-${{github.event.inputs.buildType}}.apk

